# Generated by Django 2.1.5 on 2019-01-18 22:02

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcpid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('available', models.BooleanField(default=False)),
                ('label', models.CharField(default='unidentified', help_text='Human readable label', max_length=256)),
                ('created_timestamp', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified_timestamp', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
        ),
    ]
