# Generated by Django 2.1.5 on 2019-01-19 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcpid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('available', models.BooleanField(default=False)),
                ('label', models.CharField(default='unidentified', help_text='Human readable label', max_length=256)),
                ('created_timestamp', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified_timestamp', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Current owner ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
