# Generated by Django 2.1.5 on 2019-01-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='lat',
            field=models.FloatField(default=122.4194),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='lon',
            field=models.FloatField(default=37.7749),
        ),
    ]
