# Generated by Django 2.1.5 on 2019-01-19 04:06

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20190119_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-121.9482421705281, 37.71859032109801, srid=4326), help_text='Represented as (longitude, latitude)', srid=4326),
        ),
    ]
