# Generated by Django 2.1.5 on 2019-01-18 23:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20190118_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
