# Generated by Django 2.1.5 on 2019-01-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='search_radius',
            field=models.FloatField(default=2.0),
        ),
    ]
