# Generated by Django 2.1.5 on 2019-01-19 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20190119_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='test',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the reservation', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
